Algoritmo "Enquanto"

//Bootcamp Programador(a) de Software Iniciante//

Var
   Nomes: Vetor[0..4] de Caractere
   
//I variávei contadora
   I: Inteiro

Inicio
   Nomes[0] <- "João"
   Nomes[1] <- "Maria"
   Nomes[2] <- "Jose"
   Nomes[3] <- "Ana"
   Nomes[4] <- "Jorge"
   
   I <- 0
   Enquanto I < 5 Faca
      Escreval (Nomes[I])
//incluir operação de incremento
      I <- I + 1
   
   FimEnquanto

Fimalgoritmo