Algoritmo "TiposVariaveis"

//Bootcamp Programador(a) de Software Iniciante//

Var
   Modelo: Caractere
   Ano: Inteiro
   Valor: Real
   IpvaPago, SeguroPago: Logico

Inicio
   Modelo <- "Gol"
   Ano <- 2010
   Valor <- 2050.14
   IpvaPago <- Falso
   SeguroPago <- Verdadeiro
   
   Escreval (Modelo)
   Escreval (Ano)
   Escreval (Valor)
   Escreval (IpvaPago)
   Escreval (SeguroPago)

Fimalgoritmo